name: "K8s Security Policy Check"

on:
  push:
    branches:
      - main
      - test
      - develop
    tags:
      - "*"

  pull_request:
    branches:
      - main
      - test
      - develop

jobs:
  policy-check:
    if: ${{ github.repository != 'bcgov-c/ministry-gitops-jag-template' }}
    name: policy-check
    runs-on: ubuntu-latest
    env:
      policy-directory: ./.github/workflows
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: azure/setup-helm@v3
        with:
          version: "latest " # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install

      - name: Policy Enforcement
        id: policy
        run: |
          # install and configure Datree plugin 
          helm plugin install https://github.com/datreeio/helm-datree
          helm plugin update datree

          helm datree config set offline local 

          # Run datree config scan against ISB K8s policies

          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "This is the main branch"
            helm datree test --ignore-missing-schemas --policy-config ../policies.yaml --include-tests ../../charts/gitops -- --namespace prod --values ../../deploy/prod_values.yaml gitops-app-prod
          elif [[ "$GITHUB_REF" == "refs/heads/develop" || "$GITHUB_REF" == "refs/heads/gitops" ]]; then
            echo "This is the dev branch"
            helm datree test --ignore-missing-schemas --policy-config ../policies.yaml  --include-tests ../../charts/gitops -- --namespace dev --values ../../deploy/dev_values.yaml gitops-app-dev
          elif [[ "$GITHUB_REF" == "refs/heads/test" ]]; then
            echo "This is the test branch"
            helm datree test --ignore-missing-schemas --policy-config ../policies.yaml --include-tests ../../charts/gitops -- --namespace test --values ../../deploy/test_values.yaml gitops-app-test
          else
            echo "This is another branch"
            # Add commands for other branches here, if needed
          fi

        working-directory: ${{env.policy-directory}}
